/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pertemuan9;

/**
 *
 * @author Ridho
 */
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import net.sf.jasperreports.engine.JRException;


public class KelasemenLigaSawah extends javax.swing.JFrame {

    Connection conn;
    Statement stmt;
    PreparedStatement pstmt = null;
    DefaultTableModel model;

    String driver = "org.postgresql.Driver";
    String koneksi = "jdbc:postgresql://localhost:5432/TugasPBO";
    String user = "postgres";
    String password = "er021105";
    InputStreamReader inputStreamReader = new InputStreamReader(System.in);
    BufferedReader input = new BufferedReader(inputStreamReader);
    private int oldNomor = -1;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KelasemenLigaSawah.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public KelasemenLigaSawah() {
        initComponents();
        TampilkanTabel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InsertDialog = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        NomorPendaftaran = new javax.swing.JTextField();
        Klub = new javax.swing.JTextField();
        AsalKlub = new javax.swing.JTextField();
        Point = new javax.swing.JTextField();
        Simpan = new javax.swing.JButton();
        BatalInsert = new javax.swing.JButton();
        UpdateDialog = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        NomorPendaftaran1 = new javax.swing.JTextField();
        Klub1 = new javax.swing.JTextField();
        AsalKlub1 = new javax.swing.JTextField();
        Point1 = new javax.swing.JTextField();
        SimpanUpdate = new javax.swing.JButton();
        BatalUpdate = new javax.swing.JButton();
        DeleteDialog = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        NomorPendaftaran2 = new javax.swing.JTextField();
        Klub2 = new javax.swing.JTextField();
        AsalKlub2 = new javax.swing.JTextField();
        Point2 = new javax.swing.JTextField();
        SimpanDelete = new javax.swing.JButton();
        BatalDelete = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnDelete = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelKlasemen = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Keluar = new javax.swing.JButton();
        btnInsert1 = new javax.swing.JButton();

        jLabel7.setText("Nomor Pendaftaran");

        jLabel8.setText("Klub");

        jLabel9.setText("Asal Klub");

        jLabel10.setText("Point");

        NomorPendaftaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomorPendaftaranActionPerformed(evt);
            }
        });

        Klub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KlubActionPerformed(evt);
            }
        });

        Simpan.setText("Insert");
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });

        BatalInsert.setText("Batal");
        BatalInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatalInsertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InsertDialogLayout = new javax.swing.GroupLayout(InsertDialog.getContentPane());
        InsertDialog.getContentPane().setLayout(InsertDialogLayout);
        InsertDialogLayout.setHorizontalGroup(
            InsertDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertDialogLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(InsertDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(InsertDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InsertDialogLayout.createSequentialGroup()
                        .addComponent(Simpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BatalInsert))
                    .addComponent(NomorPendaftaran, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(Klub)
                    .addComponent(AsalKlub)
                    .addComponent(Point))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        InsertDialogLayout.setVerticalGroup(
            InsertDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertDialogLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(InsertDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(NomorPendaftaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(InsertDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(Klub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(InsertDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(AsalKlub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(InsertDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(Point, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(InsertDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Simpan)
                    .addComponent(BatalInsert))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jLabel11.setText("Nomor Pendaftaran");

        jLabel12.setText("Klub");

        jLabel13.setText("Asal Klub");

        jLabel14.setText("Point");

        NomorPendaftaran1.setEditable(false);
        NomorPendaftaran1.setActionCommand("<Not Set>");
        NomorPendaftaran1.setEnabled(false);
        NomorPendaftaran1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomorPendaftaran1ActionPerformed(evt);
            }
        });

        Klub1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Klub1ActionPerformed(evt);
            }
        });

        SimpanUpdate.setText("Update");
        SimpanUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanUpdateActionPerformed(evt);
            }
        });

        BatalUpdate.setText("Batal");
        BatalUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatalUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UpdateDialogLayout = new javax.swing.GroupLayout(UpdateDialog.getContentPane());
        UpdateDialog.getContentPane().setLayout(UpdateDialogLayout);
        UpdateDialogLayout.setHorizontalGroup(
            UpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateDialogLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(UpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(UpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(UpdateDialogLayout.createSequentialGroup()
                        .addComponent(SimpanUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(BatalUpdate))
                    .addComponent(NomorPendaftaran1)
                    .addComponent(Klub1)
                    .addComponent(AsalKlub1)
                    .addComponent(Point1))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        UpdateDialogLayout.setVerticalGroup(
            UpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateDialogLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(UpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(NomorPendaftaran1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(UpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(Klub1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(UpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(AsalKlub1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(UpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(Point1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(UpdateDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SimpanUpdate)
                    .addComponent(BatalUpdate))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jLabel15.setText("Nomor Pendaftaran");

        jLabel16.setText("Klub");

        jLabel17.setText("Asal Klub");

        jLabel18.setText("Point");

        NomorPendaftaran2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomorPendaftaran2ActionPerformed(evt);
            }
        });

        Klub2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Klub2ActionPerformed(evt);
            }
        });

        SimpanDelete.setText("Delete");
        SimpanDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanDeleteActionPerformed(evt);
            }
        });

        BatalDelete.setText("Batal");
        BatalDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatalDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DeleteDialogLayout = new javax.swing.GroupLayout(DeleteDialog.getContentPane());
        DeleteDialog.getContentPane().setLayout(DeleteDialogLayout);
        DeleteDialogLayout.setHorizontalGroup(
            DeleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteDialogLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(DeleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DeleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(DeleteDialogLayout.createSequentialGroup()
                        .addComponent(SimpanDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(BatalDelete))
                    .addComponent(NomorPendaftaran2)
                    .addComponent(Klub2)
                    .addComponent(AsalKlub2)
                    .addComponent(Point2))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        DeleteDialogLayout.setVerticalGroup(
            DeleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteDialogLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(DeleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(NomorPendaftaran2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DeleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(Klub2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DeleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(AsalKlub2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DeleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(Point2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DeleteDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SimpanDelete)
                    .addComponent(BatalDelete))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 102));

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnCetak.setText("Print");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        TabelKlasemen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nomor", "klub", "Asal", "Point"
            }
        ));
        TabelKlasemen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelKlasemenMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TabelKlasemen);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("STSong", 0, 48)); // NOI18N
        jLabel6.setText("KELASEMEN");

        jLabel5.setFont(new java.awt.Font("STSong", 0, 36)); // NOI18N
        jLabel5.setText("LIGA SAWAH");

        Keluar.setText("Keluar");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });

        btnInsert1.setText("Insert");
        btnInsert1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsert1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCetak, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Keluar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnInsert1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(201, 201, 201))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(228, 228, 228))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInsert1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(Keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void TampilkanTabel() {
        try {
            Class.forName(driver);
            String sql = "SELECT * FROM LigaSawah";
            conn = DriverManager.getConnection(koneksi, user, password);
            stmt = conn.createStatement();

            ResultSet rs = stmt.executeQuery(sql);
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Nomor");
            model.addColumn("Klub");
            model.addColumn("KotaAsal");
            model.addColumn("PointKemenangan");

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("Nomor"),
                    rs.getString("Klub"),
                    rs.getString("KotaAsal"),
                    rs.getInt("PointKemenangan")
                });
            }
            this.TabelKlasemen.setModel(model);

            rs.close();
            stmt.close();
            conn.close();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(KelasemenLigaSawah.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        // TODO add your handling code here:
        UpdateDialog.pack();
        UpdateDialog.setLocationRelativeTo(this);
        UpdateDialog.setModal(true);
        UpdateDialog.setVisible(true);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
//Delete Data
        int row = TabelKlasemen.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih dulu data yang mau dihapus!");
            return;
        }

        DeleteDialog.pack();
        DeleteDialog.setLocationRelativeTo(this);
        DeleteDialog.setModal(true);
        DeleteDialog.setVisible(true);

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        JasperReport reports;
        String path = ".\\src\\Pertemuan9\\reportKlasemen.jasper";

        try {
            // Koneksi database
            Class.forName("org.postgresql.Driver");
            Connection conn = DriverManager.getConnection(
                    "jdbc:postgresql://localhost:5432/TugasPBO", // ganti sesuai database kamu
                    "postgres", 
                    "er021105" 
            );

            // Load dan tampilkan laporan Jasper
            reports = (JasperReport) JRLoader.loadObjectFromFile(path);
            JasperPrint jprint = JasperFillManager.fillReport(path, null, conn);
            JasperViewer jviewer = new JasperViewer(jprint, false);
            jviewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            jviewer.setVisible(true);

        } catch (ClassNotFoundException | SQLException | JRException ex) {
            Logger.getLogger(KelasemenLigaSawah.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,
                    "Terjadi kesalahan saat mencetak laporan:\n" + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnCetakActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed

        int jawab = JOptionPane.showConfirmDialog(this, "Yakin ingin keluar?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (jawab == JOptionPane.YES_OPTION) {
            System.exit(0);
        }

    }//GEN-LAST:event_KeluarActionPerformed

    private void TabelKlasemenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelKlasemenMouseClicked

        int baris = TabelKlasemen.getSelectedRow(); // ambil baris yang diklik
        if (baris != -1) {
            NomorPendaftaran.setText(TabelKlasemen.getValueAt(baris, 0).toString());
            Klub.setText(TabelKlasemen.getValueAt(baris, 1).toString());
            AsalKlub.setText(TabelKlasemen.getValueAt(baris, 2).toString());
            Point.setText(TabelKlasemen.getValueAt(baris, 3).toString());

            NomorPendaftaran1.setText(TabelKlasemen.getValueAt(baris, 0).toString());
            Klub1.setText(TabelKlasemen.getValueAt(baris, 1).toString());
            AsalKlub1.setText(TabelKlasemen.getValueAt(baris, 2).toString());
            Point1.setText(TabelKlasemen.getValueAt(baris, 3).toString());

            NomorPendaftaran2.setText(TabelKlasemen.getValueAt(baris, 0).toString());
            Klub2.setText(TabelKlasemen.getValueAt(baris, 1).toString());
            AsalKlub2.setText(TabelKlasemen.getValueAt(baris, 2).toString());
            Point2.setText(TabelKlasemen.getValueAt(baris, 3).toString());
        }

    }//GEN-LAST:event_TabelKlasemenMouseClicked

    private void NomorPendaftaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomorPendaftaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomorPendaftaranActionPerformed

    private void KlubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KlubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KlubActionPerformed

    private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
        try {
            if (NomorPendaftaran.getText().trim().isEmpty()
                    || Klub.getText().trim().isEmpty()
                    || AsalKlub.getText().trim().isEmpty()
                    || Point.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Semua field harus diisi!");
                return;
            }

            // Cek apakah nomor sudah ada
            if (isNomorExists(Integer.parseInt(NomorPendaftaran.getText()))) {
                JOptionPane.showMessageDialog(this, "Nomor pendaftaran sudah ada! Gunakan nomor lain.");
                return;
            }

            // Cek apakah klub sudah ada
            if (isKlubExists(Klub.getText().trim())) {
                JOptionPane.showMessageDialog(this, "Nama klub sudah ada! Gunakan nama klub lain.");
                return;
            }

            Class.forName(driver);
            conn = DriverManager.getConnection(koneksi, user, password);
            String sql = "INSERT INTO LigaSawah (Nomor, Klub, KotaAsal, PointKemenangan) VALUES (?, ?, ?, ?)";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, Integer.parseInt(NomorPendaftaran.getText()));
            pst.setString(2, Klub.getText());
            pst.setString(3, AsalKlub.getText());
            pst.setInt(4, Integer.parseInt(Point.getText()));

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");

            // Refresh tabel
            TampilkanTabel();
            resetInsertFields();
            // Tutup dialog insert
            InsertDialog.setVisible(false);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Gagal tambah data: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_SimpanActionPerformed

    private void BatalInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatalInsertActionPerformed
        // TODO add your handling code here:
        InsertDialog.setVisible(false);
    }//GEN-LAST:event_BatalInsertActionPerformed

    private void NomorPendaftaran1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomorPendaftaran1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomorPendaftaran1ActionPerformed

    private void Klub1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Klub1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Klub1ActionPerformed

    private void SimpanUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanUpdateActionPerformed
        // TODO add your handling code here:
        try {

            if (NomorPendaftaran1.getText().trim().isEmpty()
                    || Klub1.getText().trim().isEmpty()
                    || AsalKlub1.getText().trim().isEmpty()
                    || Point1.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Semua field harus diisi!");
                return;
            }

            int newNomor = Integer.parseInt(NomorPendaftaran1.getText());

            // Jika nomor diubah, cek apakah nomor baru sudah ada
            if (newNomor != oldNomor && isNomorExists(newNomor)) {
                JOptionPane.showMessageDialog(this, "Nomor pendaftaran sudah ada! Gunakan nomor lain.");
                return;
            }

            // Cek apakah klub baru sudah digunakan oleh klub lain
            if (isKlubExists(Klub1.getText().trim()) && !Klub1.getText().trim().equalsIgnoreCase(TabelKlasemen.getValueAt(TabelKlasemen.getSelectedRow(), 1).toString())) {
                JOptionPane.showMessageDialog(this, "Nama klub sudah ada! Gunakan nama klub lain.");
                return;
            }

            Class.forName(driver);
            conn = DriverManager.getConnection(koneksi, user, password);

            // Update data menggunakan nomor lama sebagai referensi
            String sql = "UPDATE LigaSawah SET Nomor = ?, Klub = ?, KotaAsal = ?, PointKemenangan = ? WHERE Nomor = ?";
            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setInt(1, newNomor);
            pst.setString(2, Klub1.getText());
            pst.setString(3, AsalKlub1.getText());
            pst.setInt(4, Integer.parseInt(Point1.getText()));
            pst.setInt(5, oldNomor);  // Gunakan nomor lama untuk WHERE clause

            int affectedRows = pst.executeUpdate();

            if (affectedRows > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil diupdate!");
                TampilkanTabel();
                resetUpdateFields();
                oldNomor = -1; // Reset oldNomor
                UpdateDialog.setVisible(false); // Tutup dialog update
            } else {
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan!");
            }

            // Tutup koneksi
            pst.close();
            conn.close();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Gagal update data: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_SimpanUpdateActionPerformed

    private void BatalUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatalUpdateActionPerformed
        // TODO add your handling code here:
        UpdateDialog.setVisible(false);
    }//GEN-LAST:event_BatalUpdateActionPerformed

    private void NomorPendaftaran2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomorPendaftaran2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomorPendaftaran2ActionPerformed

    private void Klub2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Klub2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Klub2ActionPerformed

    private void SimpanDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanDeleteActionPerformed
        try {
            // Tampilkan dialog konfirmasi
            int confirmation = JOptionPane.showConfirmDialog(
                    this,
                    "Apakah Anda yakin ingin menghapus data dengan nomor: " + NomorPendaftaran2.getText() + "?",
                    "Konfirmasi Hapus Data",
                    JOptionPane.YES_NO_OPTION
            );

            if (confirmation != JOptionPane.YES_OPTION) {
                return;
            }

            Class.forName(driver);
            conn = DriverManager.getConnection(koneksi, user, password);

            String sql = "DELETE FROM LigaSawah WHERE Nomor = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, Integer.parseInt(NomorPendaftaran2.getText()));
            int affectedRows = pst.executeUpdate();

            if (affectedRows > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
                TampilkanTabel();
                resetDeleteFields();
                DeleteDialog.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan!");
            }

            pst.close();
            conn.close();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Gagal hapus data: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_SimpanDeleteActionPerformed

    private void BatalDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatalDeleteActionPerformed
        // TODO add your handling code here:
        DeleteDialog.setVisible(false);
    }//GEN-LAST:event_BatalDeleteActionPerformed

    private void btnInsert1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsert1ActionPerformed
        // TODO add your handling code here:
        InsertDialog.pack();
        InsertDialog.setLocationRelativeTo(this);
        InsertDialog.setModal(true);
        InsertDialog.setVisible(true);
        
    }//GEN-LAST:event_btnInsert1ActionPerformed

    /**
     * @param args the command line arguments
     */
    // Method untuk reset field insert dialog
    
    private boolean isNomorExists(int nomor) {
        try {
            Class.forName(driver);
            conn = DriverManager.getConnection(koneksi, user, password);
            String sql = "SELECT COUNT(*) FROM LigaSawah WHERE Nomor = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, nomor);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                return rs.getInt(1) > 0;
            }

            rs.close();
            pst.close();
            conn.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error checking nomor: " + ex.getMessage());
        }
        return false;
    }
    
    private void resetInsertFields() {
        NomorPendaftaran.setText("");
        Klub.setText("");
        AsalKlub.setText("");
        Point.setText("");
    }

// Method untuk reset field update dialog
    private void resetUpdateFields() {
        NomorPendaftaran1.setText("");
        Klub1.setText("");
        AsalKlub1.setText("");
        Point1.setText("");
    }

// Method untuk reset field delete dialog
    private void resetDeleteFields() {
        NomorPendaftaran2.setText("");
        Klub2.setText("");
        AsalKlub2.setText("");
        Point2.setText("");
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new KelasemenLigaSawah().setVisible(true));
    }
    
    private boolean isKlubExists(String klub) {
        try {
            Class.forName(driver);
            conn = DriverManager.getConnection(koneksi, user, password);
            String sql = "SELECT COUNT(*) FROM LigaSawah WHERE LOWER(Klub) = LOWER(?)";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, klub);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                return rs.getInt(1) > 0;
            }

            rs.close();
            pst.close();
            conn.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error checking klub: " + ex.getMessage());
        }
        return false;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AsalKlub;
    private javax.swing.JTextField AsalKlub1;
    private javax.swing.JTextField AsalKlub2;
    private javax.swing.JButton BatalDelete;
    private javax.swing.JButton BatalInsert;
    private javax.swing.JButton BatalUpdate;
    private javax.swing.JDialog DeleteDialog;
    private javax.swing.JDialog InsertDialog;
    private javax.swing.JButton Keluar;
    private javax.swing.JTextField Klub;
    private javax.swing.JTextField Klub1;
    private javax.swing.JTextField Klub2;
    private javax.swing.JTextField NomorPendaftaran;
    private javax.swing.JTextField NomorPendaftaran1;
    private javax.swing.JTextField NomorPendaftaran2;
    private javax.swing.JTextField Point;
    private javax.swing.JTextField Point1;
    private javax.swing.JTextField Point2;
    private javax.swing.JButton Simpan;
    private javax.swing.JButton SimpanDelete;
    private javax.swing.JButton SimpanUpdate;
    private javax.swing.JTable TabelKlasemen;
    private javax.swing.JDialog UpdateDialog;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert1;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
